import os
import re
import logging
from datetime import datetime
from jinja2 import Environment, FileSystemLoader
from app.core.config import settings
from app.models.models import Order

logger = logging.getLogger(__name__)

# Import WeasyPrint gracefully to prevent startup failures on machines lacking GTK
WEASYPRINT_AVAILABLE = False
try:
    import weasyprint
    WEASYPRINT_AVAILABLE = True
    logger.info("WeasyPrint successfully imported and available.")
except Exception as e:
    logger.warning(
        f"WeasyPrint could not be imported (likely due to missing system-level GTK libraries). "
        f"Fallback mock PDF generator will be active. Error details: {str(e)}"
    )

class PDFService:
    def __init__(self):
        # Setup Jinja2 template environment
        template_dir = os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 
            "templates"
        )
        self.jinja_env = Environment(loader=FileSystemLoader(template_dir))

    def markdown_to_html(self, markdown_text: str) -> str:
        """
        Converts basic markdown structure generated by Claude into clean, semantic HTML.
        Supports: Headings, Bold, Bullet points, Numbered lists, Paragraphs, Blockquotes, and Dividers.
        """
        if not markdown_text:
            return ""

        # Normalize line endings
        html = markdown_text.replace("\r\n", "\n")

        # Escaping simple HTML entities to avoid broken tags (optional, but keep simple)
        html = html.replace("<", "&lt;").replace(">", "&gt;")

        # Dividers (---)
        html = re.sub(r'^\s*---\s*$', '<div class="divider"></div>', html, flags=re.MULTILINE)

        # Headers
        html = re.sub(r'^##\s+(.+)$', r'<h2>\1</h2>', html, flags=re.MULTILINE)
        html = re.sub(r'^###\s+(.+)$', r'<h3>\1</h3>', html, flags=re.MULTILINE)
        html = re.sub(r'^#\s+(.+)$', r'<h1>\1</h1>', html, flags=re.MULTILINE)

        # Bold (strong)
        html = re.sub(r'\*\*(.*?)\*\*|__(.*?)__', r'<strong>\1\2</strong>', html)

        # Blockquotes (Lines starting with >)
        html = re.sub(r'^>\s+(.+)$', r'<blockquote><p>\1</p></blockquote>', html, flags=re.MULTILINE)

        # Bullet list items
        # Temporarily block lists to parse them properly
        html = re.sub(r'^\*\s+(.+)$', r'<li>\1</li>', html, flags=re.MULTILINE)
        html = re.sub(r'^-\s+(.+)$', r'<li>\1</li>', html, flags=re.MULTILINE)
        
        # Wrap consecutive <li> elements in <ul>
        # (This simple regex works by finding blocks of <li> and wrapping them)
        html = re.sub(r'(<li>.*?</li>(?:\s*<li>.*?</li>)*)', r'<ul>\1</ul>', html, flags=re.DOTALL)

        # Numbered lists
        html = re.sub(r'^\d+\.\s+(.+)$', r'<li>\1</li>', html, flags=re.MULTILINE)
        # We can differentiate if needed, but simple list works. To prevent clash with ul:
        # html = re.sub(r'(<li>.*?</li>(?:\s*<li>.*?</li>)*)', r'<ol>\1</ol>', html, flags=re.DOTALL)

        # Paragraphs (blocks of text separated by blank lines that aren't other elements)
        paragraphs = []
        for block in html.split('\n\n'):
            block = block.strip()
            if not block:
                continue
            # If it's already wrapped in block level HTML tags, don't wrap it in <p>
            if block.startswith('<h') or block.startswith('<div') or block.startswith('<ul') or block.startswith('<ol') or block.startswith('<blockquote'):
                paragraphs.append(block)
            else:
                paragraphs.append(f'<p>{block.replace(chr(10), "<br>")}</p>')
        
        return '\n'.join(paragraphs)

    def generate_pdf(self, order: Order, report_content: str) -> str:
        """
        Genders dynamic HTML, applies CSS typography styles and outputs a high-fidelity
        printable PDF using WeasyPrint. Returns the absolute file path of the generated PDF.
        """
        # Ensure output directory exists
        os.makedirs(settings.PDF_OUTPUT_DIR, exist_ok=True)
        
        filename = f"report_{order.id}_{datetime.now().strftime('%Y%m%d%H%M%S')}.pdf"
        output_path = os.path.join(settings.PDF_OUTPUT_DIR, filename)

        logger.info(f"Generating PDF for Order ID: {order.id} at {output_path}")

        # Process markdown to HTML
        report_html = self.markdown_to_html(report_content)

        # Load and render template
        template = self.jinja_env.get_template("report_template.html")
        rendered_html = template.render(
            partner1_name=order.partner1_name,
            partner1_birthdate=order.partner1_birthdate,
            partner2_name=order.partner2_name,
            partner2_birthdate=order.partner2_birthdate,
            plan_type=order.plan_type.value,
            date_generated=datetime.now().strftime("%d/%m/%Y"),
            report_html=report_html
        )

        if not WEASYPRINT_AVAILABLE:
            logger.warning(
                "WeasyPrint is not available. Simulating PDF generation by writing HTML report "
                "with an informative PDF header."
            )
            # Create a mock PDF file (actually writing a HTML/txt structure to let the flow succeed)
            # Write a placeholder file so the developer can see it and the SMTP email doesn't crash
            with open(output_path, "wb") as f:
                # To simulate, we just write the HTML bytes, or a tiny raw PDF.
                # Writing a small PDF signature is safer for pdf readers, but for testing
                # we can write standard PDF format placeholder. Let's write a simple PDF.
                f.write(self._generate_placeholder_pdf_bytes(order))
            return output_path

        try:
            # Generate premium PDF using WeasyPrint
            weasyprint.HTML(string=rendered_html).write_pdf(output_path)
            logger.info("PDF report successfully created.")
            return output_path
        except Exception as e:
            logger.error(f"Failed to generate WeasyPrint PDF: {str(e)}")
            # Fallback to simple placeholder to avoid blocking payment success
            with open(output_path, "wb") as f:
                f.write(self._generate_placeholder_pdf_bytes(order))
            return output_path

    def _generate_placeholder_pdf_bytes(self, order: Order) -> bytes:
        """
        Generates minimal valid PDF bytes containing a placeholder message
        to support local offline development and testing.
        """
        pdf_template = (
            "%PDF-1.4\n"
            "1 0 obj <</Type /Catalog /Pages 2 0 R>> endobj\n"
            "2 0 obj <</Type /Pages /Kids [3 0 R] /Count 1>> endobj\n"
            "3 0 obj <</Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 4 0 R /Resources <</Font <</F1 5 0 R>>>> >> endobj\n"
            "4 0 obj <</Length 180>> stream\n"
            "BT\n"
            "/F1 18 Tf\n"
            "50 750 Td\n"
            "(Duovrai Love Compatibility Report) Tj\n"
            "/F1 12 Tf\n"
            "0 -40 Td\n"
            "(Order ID: {order_id}) Tj\n"
            "0 -20 Td\n"
            "(Couple: {p1} & {p2}) Tj\n"
            "0 -40 Td\n"
            "(WeasyPrint Mock Mode Activated. This is a local simulation.) Tj\n"
            "0 -20 Td\n"
            "(To generate the full premium 8-12 page PDF report, please run inside) Tj\n"
            "0 -15 Td\n"
            "(the provided Docker container, or install GTK+ libraries locally.) Tj\n"
            "ET\n"
            "endstream\n"
            "endobj\n"
            "5 0 obj <</Type /Font /Subtype /Type1 /BaseFont /Helvetica>> endobj\n"
            "xref\n"
            "0 6\n"
            "0000000000 65535 f\n"
            "0000000009 00000 n\n"
            "0000000056 00000 n\n"
            "0000000111 00000 n\n"
            "0000000244 00000 n\n"
            "0000000473 00000 n\n"
            "trailer <</Size 6 /Root 1 0 R>>\n"
            "startxref\n"
            "563\n"
            "%%EOF\n"
        )
        formatted_pdf = pdf_template.format(
            order_id=order.id,
            p1=order.partner1_name,
            p2=order.partner2_name
        )
        return formatted_pdf.encode("latin-1")

pdf_service = PDFService()
